name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or 'main' if you use that

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and push Docker image to Artifact Registry
      run: |
        docker build -t europe-west1-docker.pkg.dev/olympics-data-shushant/olympics-docker/olympics-app:$GITHUB_SHA .
        docker push europe-west1-docker.pkg.dev/olympics-data-shushant/olympics-docker/olympics-app:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy olympics-app \
          --image europe-west1-docker.pkg.dev/olympics-data-shushant/olympics-docker/olympics-app:$GITHUB_SHA \
          --region europe-west1 \
          --platform managed \
          --allow-unauthenticated \
          --port 8080
